<?php  echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'; ?>
<html ="http://www.w3.org/1999/xhtml" lang="en">

<head>

<title>µMVC</title>
<meta http-equiv="Content-Language" content="en-gb" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta name="keywords" content="" />
<meta name="description" content="" />


<!-- stylesheets -->
<link rel="stylesheet" type="text/css" href="css/style.css" />

<!-- javascripts -->
<script src="js/mootools-1.2.4-core-yc.js" language="JavaScript"></script>
<script src="js/mootools-1.2.4.2-more.js" language="JavaScript"></script>
</head>


<body>
<div id="header">
	<h1>µMVC - plain, simple MVC</h1>
</div>

<div id="page">
	<div id="menu">
		<ul>
			<li><a title="Home" href="?a=index">Home</a></li>
			<li><a title="Documentation" href="?a=docu">Documentation</a></li>
			<li><a title="Download" href="?a=download">Download</a></li>
		</ul>
	</div>
	
	<div id="content">
		<?php 
		//move it where you want your content to be
		require_once(CONTENT_TO_VIEW);
		?>
	</div>
	
	<div id="footer">
		<p>Footer. What have you thought?</p>
	</div>
</div>

</body>
</html>